// Auto-generated from Peptides_Master_List_FULL_Explainers_CV_Interactions_Dropdowns.xlsx

export interface PeptideKnowledge {
  name: string
  primaryPurpose: string
  whatItDoes: string
  commonUses: string
  dosageRange: string
  riskCautions: string
  bestFor: string
  keyEffects: string
  evidenceLevel: string
  bottomLine: string
  avoidIf: string
  cvRating: number
  cvNotes: string
  drugInteractions: string
  goalCategory: string
  categories: string[]
}

export const PEPTIDE_KNOWLEDGE: PeptideKnowledge[] = [
  {
    name: "Semaglutide (Wegovy/Ozempic)",
    primaryPurpose: "Metabolic / Weight loss",
    whatItDoes: "GLP-1 receptor agonist: increases satiety, slows gastric emptying, improves insulin secretion",
    commonUses: "Chronic weight management; Type 2 diabetes",
    dosageRange: "0.25 mg weekly titration up to 1.7–2.4 mg weekly (Wegovy)",
    riskCautions: "GI side effects; risk of pancreatitis; gallbladder disease; contraindicated in MTC/MEN2 history",
    bestFor: "Cardiometabolic risk reduction (weight, glucose, BP)",
    keyEffects: "Less hunger, slower digestion, better blood sugar; often improves BP and overall CV risk",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "GI side effects; risk of pancreatitis; gallbladder disease; contraindicated in MTC/MEN2 history",
    cvRating: 5,
    cvNotes: "Strong human outcomes data via diabetes/obesity trials; improves multiple CV risk factors (weight, glucose, BP).",
    drugInteractions: "Caution with insulin/sulfonylureas (hypoglycemia risk); delays gastric emptying may affect absorption of oral meds; monitor for dehydration if on diuretics.",
    goalCategory: "Metabolic/Weight",
    categories: ["Metabolic/Weight"],
  },
  {
    name: "Tirzepatide (Zepbound/Mounjaro)",
    primaryPurpose: "Metabolic / Weight loss",
    whatItDoes: "Dual GIP/GLP-1 agonist: appetite reduction + improved glycemic control",
    commonUses: "Chronic weight management; Type 2 diabetes",
    dosageRange: "2.5 mg weekly start → 5 mg; may increase by 2.5 mg q≥4 weeks; max 15 mg weekly",
    riskCautions: "GI side effects; pancreatitis risk; gallbladder disease; thyroid C-cell tumor warning; hypoglycemia with insulin/sulfonylureas",
    bestFor: "Cardiometabolic risk reduction (weight, glucose, BP)",
    keyEffects: "Less hunger, slower digestion, better blood sugar; often improves BP and overall CV risk",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "GI side effects; pancreatitis risk; gallbladder disease; thyroid C-cell tumor warning; hypoglycemia with insulin/sulfonylureas",
    cvRating: 5,
    cvNotes: "Strong human outcomes data via diabetes/obesity trials; improves multiple CV risk factors (weight, glucose, BP).",
    drugInteractions: "Caution with insulin/sulfonylureas (hypoglycemia risk); delays gastric emptying may affect absorption of oral meds; monitor for dehydration if on diuretics.",
    goalCategory: "Metabolic/Weight",
    categories: ["Metabolic/Weight"],
  },
  {
    name: "Liraglutide (Saxenda/Victoza)",
    primaryPurpose: "Metabolic / Weight loss",
    whatItDoes: "GLP-1 receptor agonist: reduces appetite and improves glycemic control",
    commonUses: "Weight management; Type 2 diabetes",
    dosageRange: "0.6 mg daily titration up to 3 mg daily (Saxenda)",
    riskCautions: "GI side effects; pancreatitis; gallbladder disease; thyroid C-cell tumor warning",
    bestFor: "Cardiometabolic risk reduction (weight, glucose, BP)",
    keyEffects: "Less hunger, slower digestion, better blood sugar; often improves BP and overall CV risk",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "GI side effects; pancreatitis; gallbladder disease; thyroid C-cell tumor warning",
    cvRating: 5,
    cvNotes: "Strong human outcomes data via diabetes/obesity trials; improves multiple CV risk factors (weight, glucose, BP).",
    drugInteractions: "Caution with insulin/sulfonylureas (hypoglycemia risk); delays gastric emptying may affect absorption of oral meds; monitor for dehydration if on diuretics.",
    goalCategory: "Metabolic/Weight",
    categories: ["Metabolic/Weight"],
  },
  {
    name: "Exenatide (Byetta/Bydureon)",
    primaryPurpose: "Metabolic / Diabetes",
    whatItDoes: "GLP-1 receptor agonist: improves insulin secretion and satiety",
    commonUses: "Type 2 diabetes",
    dosageRange: "Labeled dosing varies by formulation (see product PI)",
    riskCautions: "GI effects; pancreatitis; renal considerations",
    bestFor: "Cardiometabolic risk reduction (weight, glucose, BP)",
    keyEffects: "Less hunger, slower digestion, better blood sugar; often improves BP and overall CV risk",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "GI effects; pancreatitis; renal considerations",
    cvRating: 5,
    cvNotes: "Strong human outcomes data via diabetes/obesity trials; improves multiple CV risk factors (weight, glucose, BP).",
    drugInteractions: "Caution with insulin/sulfonylureas (hypoglycemia risk); delays gastric emptying may affect absorption of oral meds; monitor for dehydration if on diuretics.",
    goalCategory: "Metabolic/Weight",
    categories: ["Metabolic/Weight"],
  },
  {
    name: "Dulaglutide (Trulicity)",
    primaryPurpose: "Metabolic / Diabetes",
    whatItDoes: "GLP-1 receptor agonist: improves glycemic control",
    commonUses: "Type 2 diabetes",
    dosageRange: "Labeled dosing varies by product PI",
    riskCautions: "GI effects; pancreatitis; thyroid C-cell tumor warning",
    bestFor: "Cardiometabolic risk reduction (weight, glucose, BP)",
    keyEffects: "Less hunger, slower digestion, better blood sugar; often improves BP and overall CV risk",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "GI effects; pancreatitis; thyroid C-cell tumor warning",
    cvRating: 5,
    cvNotes: "Strong human outcomes data via diabetes/obesity trials; improves multiple CV risk factors (weight, glucose, BP).",
    drugInteractions: "Caution with insulin/sulfonylureas (hypoglycemia risk); delays gastric emptying may affect absorption of oral meds; monitor for dehydration if on diuretics.",
    goalCategory: "Metabolic/Weight",
    categories: ["Metabolic/Weight"],
  },
  {
    name: "Pramlintide (Symlin)",
    primaryPurpose: "Metabolic / Diabetes",
    whatItDoes: "Amylin analog: slows gastric emptying, suppresses glucagon, promotes satiety",
    commonUses: "Type 1 and Type 2 diabetes adjunct to mealtime insulin",
    dosageRange: "T1D: start 15 mcg pre-meals; titrate; T2D: start 60 mcg pre-meals → 120 mcg",
    riskCautions: "Hypoglycemia risk (requires insulin dose reduction); nausea; careful glucose monitoring",
    bestFor: "Cardiometabolic risk reduction (weight, glucose, BP)",
    keyEffects: "More satiety + slower digestion; improves post-meal blood sugar",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "Hypoglycemia risk (requires insulin dose reduction); nausea; careful glucose monitoring",
    cvRating: 3,
    cvNotes: "Improves post-meal glucose and satiety; indirect CV benefit via glycemic control (less direct outcomes data).",
    drugInteractions: "Requires mealtime insulin dose reduction (hypoglycemia risk); delays gastric emptying—separate timing for oral meds that need rapid absorption.",
    goalCategory: "Metabolic/Weight",
    categories: ["Metabolic/Weight"],
  },
  {
    name: "Cagrilintide (research)",
    primaryPurpose: "Metabolic / Weight loss",
    whatItDoes: "Long-acting amylin analog; increases satiety",
    commonUses: "Obesity research / combinations",
    dosageRange: "N/A (no established labeled dosing)",
    riskCautions: "Not FDA-approved; unknown long-term safety; avoid self-administration",
    bestFor: "Cardiometabolic risk reduction (weight, glucose, BP)",
    keyEffects: "More satiety + slower digestion; improves post-meal blood sugar",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "Limited direct cardiovascular evidence.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Metabolic/Weight",
    categories: ["Metabolic/Weight"],
  },
  {
    name: "Retatrutide (research)",
    primaryPurpose: "Metabolic / Weight loss",
    whatItDoes: "Triple agonist (GLP-1/GIP/glucagon) to reduce weight and increase energy expenditure",
    commonUses: "Obesity research",
    dosageRange: "N/A (no established labeled dosing)",
    riskCautions: "Not FDA-approved; GI effects common in class; avoid self-administration",
    bestFor: "Cardiometabolic risk reduction (weight, glucose, BP)",
    keyEffects: "Less hunger, slower digestion, better blood sugar; often improves BP and overall CV risk",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "Limited direct cardiovascular evidence.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Metabolic/Weight",
    categories: ["Metabolic/Weight"],
  },
  {
    name: "Leptin / Metreleptin",
    primaryPurpose: "Endocrine / Metabolic",
    whatItDoes: "Leptin replacement therapy in specific leptin-deficiency states",
    commonUses: "Rare metabolic disorders",
    dosageRange: "Product-specific dosing (specialist use)",
    riskCautions: "Restricted indications; immune/antibody risks; specialist-only",
    bestFor: "Cardiometabolic risk reduction (weight, glucose, BP)",
    keyEffects: "Leptin replacement therapy in specific leptin-deficiency states",
    evidenceLevel: "Mixed/unclear regulatory status",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Restricted indications; immune/antibody risks; specialist-only",
    cvRating: 1,
    cvNotes: "Limited direct cardiovascular evidence.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Metabolic/Weight",
    categories: ["Metabolic/Weight"],
  },
  {
    name: "Glucagon",
    primaryPurpose: "Endocrine / Emergency",
    whatItDoes: "Raises blood glucose via hepatic glycogenolysis",
    commonUses: "Severe hypoglycemia rescue",
    dosageRange: "Product-specific dosing (emergency use)",
    riskCautions: "Nausea/vomiting; effectiveness depends on glycogen stores",
    bestFor: "Hormone axis support (medical oversight)",
    keyEffects: "Raises blood glucose via hepatic glycogenolysis",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "Nausea/vomiting; effectiveness depends on glycogen stores",
    cvRating: 3,
    cvNotes: "Clinically important in acute care settings; not a chronic 'heart health' therapy.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "GI/Bone/Other",
    categories: ["GI/Bone/Other"],
  },
  {
    name: "Tesamorelin (Egrifta SV/WR)",
    primaryPurpose: "GH axis / Body composition",
    whatItDoes: "GHRH analog: stimulates endogenous GH; reduces visceral adipose tissue in HIV lipodystrophy",
    commonUses: "HIV-associated lipodystrophy (visceral fat)",
    dosageRange: "Egrifta SV: 1.4 mg SC once daily; Egrifta WR: 1.28 mg SC once daily",
    riskCautions: "Glucose intolerance/diabetes risk; fluid retention; contraindications per PI; not indicated for weight loss",
    bestFor: "Hormone axis support (medical oversight)",
    keyEffects: "Signals the GH axis; can affect body composition, fluid retention, and glucose",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "Glucose intolerance/diabetes risk; fluid retention; contraindications per PI; not indicated for weight loss",
    cvRating: 3,
    cvNotes: "Improves visceral fat in a specific indication; indirect cardiometabolic benefits; monitor glucose.",
    drugInteractions: "Can raise glucose; monitor if on diabetes meds; fluid retention may affect BP/CHF; avoid with active malignancy (per clinical guidance).",
    goalCategory: "GH Axis",
    categories: ["GH Axis"],
  },
  {
    name: "Somatropin (Human Growth Hormone)",
    primaryPurpose: "Endocrine",
    whatItDoes: "Recombinant GH for deficiency states",
    commonUses: "Pediatric/adult GH deficiency; other labeled uses",
    dosageRange: "Product-specific dosing (endocrinology)",
    riskCautions: "Edema, joint pain, glucose effects; contraindications in active malignancy; medical supervision required",
    bestFor: "Hormone axis support (medical oversight)",
    keyEffects: "Signals the GH axis; can affect body composition, fluid retention, and glucose",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "Edema, joint pain, glucose effects; contraindications in active malignancy; medical supervision required",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "Can raise glucose; monitor if on diabetes meds; fluid retention may affect BP/CHF; avoid with active malignancy (per clinical guidance).",
    goalCategory: "GH Axis",
    categories: ["GH Axis", "Muscle/Performance"],
  },
  {
    name: "Sermorelin (research/compounded)",
    primaryPurpose: "GH axis",
    whatItDoes: "GHRH analog; stimulates GH release",
    commonUses: "Research/anti-aging discussions",
    dosageRange: "N/A (no FDA-labeled dosing for compounded products)",
    riskCautions: "Quality variability; endocrine effects; avoid unsupervised use",
    bestFor: "Hormone axis support (medical oversight)",
    keyEffects: "Signals the GH axis; can affect body composition, fluid retention, and glucose",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "GH Axis",
    categories: ["GH Axis"],
  },
  {
    name: "CJC-1295 (research)",
    primaryPurpose: "GH axis",
    whatItDoes: "GHRH analog (research compound)",
    commonUses: "Research",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved; endocrine risks; avoid self-administration",
    bestFor: "Hormone axis support (medical oversight)",
    keyEffects: "Signals the GH axis; can affect body composition, fluid retention, and glucose",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "GH Axis",
    categories: ["GH Axis"],
  },
  {
    name: "Ipamorelin (research)",
    primaryPurpose: "GH axis",
    whatItDoes: "Ghrelin receptor agonist (GHS): stimulates GH release",
    commonUses: "Research",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved; endocrine risks; avoid self-administration",
    bestFor: "Hormone axis support (medical oversight)",
    keyEffects: "Signals the GH axis; can affect body composition, fluid retention, and glucose",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "GH Axis",
    categories: ["GH Axis", "Sleep"],
  },
  {
    name: "GHRP-2 (research)",
    primaryPurpose: "GH axis",
    whatItDoes: "Growth hormone secretagogue",
    commonUses: "Research",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved; endocrine risks",
    bestFor: "Hormone axis support (medical oversight)",
    keyEffects: "Signals the GH axis; can affect body composition, fluid retention, and glucose",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "Can raise glucose; monitor if on diabetes meds; fluid retention may affect BP/CHF; avoid with active malignancy (per clinical guidance).",
    goalCategory: "GH Axis",
    categories: ["GH Axis"],
  },
  {
    name: "GHRP-6 (research)",
    primaryPurpose: "GH axis",
    whatItDoes: "Growth hormone secretagogue; may increase appetite",
    commonUses: "Research",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved; endocrine risks",
    bestFor: "Hormone axis support (medical oversight)",
    keyEffects: "Signals the GH axis; can affect body composition, fluid retention, and glucose",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "Can raise glucose; monitor if on diabetes meds; fluid retention may affect BP/CHF; avoid with active malignancy (per clinical guidance).",
    goalCategory: "GH Axis",
    categories: ["GH Axis"],
  },
  {
    name: "BPC-157 (research)",
    primaryPurpose: "Healing / Recovery",
    whatItDoes: "Experimental peptide often studied for tissue protection and repair",
    commonUses: "Research discussions: tendon/ligament/gut",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved; human safety/efficacy not established; avoid self-administration",
    bestFor: "Tissue repair / skin & hair support",
    keyEffects: "Experimental peptide often studied for tissue protection and repair",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Healing/Recovery",
    categories: ["Healing/Recovery"],
  },
  {
    name: "TB-500 (Thymosin beta-4 fragment, research)",
    primaryPurpose: "Healing / Recovery",
    whatItDoes: "Related to thymosin beta-4 pathways; tissue repair signaling (experimental)",
    commonUses: "Research discussions: soft tissue recovery",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved; unknown risks; avoid self-administration",
    bestFor: "Tissue repair / skin & hair support",
    keyEffects: "Related to thymosin beta-4 pathways; tissue repair signaling (experimental)",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Healing/Recovery",
    categories: ["Healing/Recovery", "Muscle/Performance"],
  },
  {
    name: "Thymosin Beta-4 (Tβ4)",
    primaryPurpose: "Healing / Immune",
    whatItDoes: "Actin-binding peptide involved in wound healing and inflammation modulation",
    commonUses: "Research; regenerative medicine interest",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved for this use; unknown risks",
    bestFor: "Immune modulation / antimicrobial research",
    keyEffects: "Actin-binding peptide involved in wound healing and inflammation modulation",
    evidenceLevel: "Mixed/unclear regulatory status",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Not FDA-approved for this use; unknown risks",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Healing/Recovery",
    categories: ["Healing/Recovery"],
  },
  {
    name: "Thymosin Alpha-1 (Thymalfasin)",
    primaryPurpose: "Immune modulation",
    whatItDoes: "Immune signaling peptide used in some countries for certain conditions",
    commonUses: "Immune modulation (country-specific approvals)",
    dosageRange: "Product/country-specific dosing",
    riskCautions: "Regulatory status varies; medical supervision required",
    bestFor: "Immune modulation / antimicrobial research",
    keyEffects: "Immune signaling peptide used in some countries for certain conditions",
    evidenceLevel: "Region-specific approval (not US FDA)",
    bottomLine: "Used clinically in some countries; not standard in the US—specialist oversight.",
    avoidIf: "Regulatory status varies; medical supervision required",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Immune/Anti-inf",
    categories: ["Immune/Anti-inf"],
  },
  {
    name: "LL-37 (research)",
    primaryPurpose: "Antimicrobial / Immune",
    whatItDoes: "Human cathelicidin antimicrobial peptide (experimental)",
    commonUses: "Research: antimicrobial biofilms",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved; potential inflammation; avoid self-administration",
    bestFor: "Immune modulation / antimicrobial research",
    keyEffects: "Innate immune antimicrobial signaling (experimental)",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Immune/Anti-inf",
    categories: ["Immune/Anti-inf"],
  },
  {
    name: "VIP (Vasoactive Intestinal Peptide)",
    primaryPurpose: "Immune / Neurovascular",
    whatItDoes: "Neuropeptide involved in vasodilation and immune signaling",
    commonUses: "Research/rare uses",
    dosageRange: "N/A",
    riskCautions: "Complex systemic effects; medical supervision required",
    bestFor: "Cardiovascular / vascular effects (often hospital/physiology)",
    keyEffects: "Widens blood vessels; can lower blood pressure",
    evidenceLevel: "Mixed/unclear regulatory status",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Complex systemic effects; medical supervision required",
    cvRating: 1,
    cvNotes: "Limited direct cardiovascular evidence.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Cardio/Vascular",
    categories: ["Cognition/Mood", "Immune/Anti-inf"],
  },
  {
    name: "KPV (research)",
    primaryPurpose: "Anti-inflammatory / GI",
    whatItDoes: "Tripeptide from α-MSH pathway; experimental anti-inflammatory effects",
    commonUses: "Research: inflammatory skin/GI",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved; unknown risks",
    bestFor: "General physiology / research interest",
    keyEffects: "Tripeptide from α-MSH pathway; experimental anti-inflammatory effects",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Skin/Hair",
    categories: [],
  },
  {
    name: "Semax (research/region-specific)",
    primaryPurpose: "Cognition / Neuroprotection",
    whatItDoes: "Neuropeptide analog studied for cognitive effects",
    commonUses: "Research; cognitive support discussions",
    dosageRange: "N/A",
    riskCautions: "Regulatory status varies; avoid unsupervised use",
    bestFor: "Focus/anxiety/neuro support (often research/region-specific)",
    keyEffects: "Neuropeptide analog studied for cognitive effects",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Cognition/Mood",
    categories: ["Cognition/Mood"],
  },
  {
    name: "Selank (research/region-specific)",
    primaryPurpose: "Anxiety / Cognition",
    whatItDoes: "Neuropeptide analog studied for anxiolytic effects",
    commonUses: "Research; anxiety support discussions",
    dosageRange: "N/A",
    riskCautions: "Regulatory status varies; avoid unsupervised use",
    bestFor: "Focus/anxiety/neuro support (often research/region-specific)",
    keyEffects: "Neuropeptide analog studied for anxiolytic effects",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Cognition/Mood",
    categories: ["Cognition/Mood"],
  },
  {
    name: "Cerebrolysin (region-specific)",
    primaryPurpose: "Neurotrophic support",
    whatItDoes: "Mixture of neuropeptides used in some countries",
    commonUses: "Stroke/TBI rehab in some regions",
    dosageRange: "Country-specific protocols",
    riskCautions: "Not FDA-approved in US; adverse effects possible; clinician use",
    bestFor: "Focus/anxiety/neuro support (often research/region-specific)",
    keyEffects: "Mixture of neuropeptides used in some countries",
    evidenceLevel: "Region-specific approval (not US FDA)",
    bottomLine: "Used clinically in some countries; not standard in the US—specialist oversight.",
    avoidIf: "Not FDA-approved in US; adverse effects possible; clinician use",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Cognition/Mood",
    categories: ["Cognition/Mood"],
  },
  {
    name: "Dihexa (research)",
    primaryPurpose: "Cognition",
    whatItDoes: "Experimental compound linked to synaptogenesis pathways",
    commonUses: "Research",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved; unknown safety",
    bestFor: "Focus/anxiety/neuro support (often research/region-specific)",
    keyEffects: "Experimental compound linked to synaptogenesis pathways",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Cognition/Mood",
    categories: ["Cognition/Mood"],
  },
  {
    name: "DSIP (research)",
    primaryPurpose: "Sleep",
    whatItDoes: "Delta sleep–inducing peptide (experimental)",
    commonUses: "Research discussions: sleep",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved; limited evidence",
    bestFor: "Sleep support (variable evidence)",
    keyEffects: "Delta sleep–inducing peptide (experimental)",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Sleep",
    categories: ["Sleep"],
  },
  {
    name: "Epitalon / Epithalon (research)",
    primaryPurpose: "Longevity / Circadian",
    whatItDoes: "Peptide studied for telomere/circadian effects",
    commonUses: "Research / longevity discussions",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved; unknown human efficacy/safety",
    bestFor: "General physiology / research interest",
    keyEffects: "Peptide studied for telomere/circadian effects",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Longevity",
    categories: ["Longevity", "Sleep"],
  },
  {
    name: "NAD+ (not a peptide, but commonly discussed)",
    primaryPurpose: "Cellular energy",
    whatItDoes: "Coenzyme involved in redox/mitochondrial function",
    commonUses: "Energy support discussions",
    dosageRange: "Oral/IV protocols vary; no single labeled dose for 'NAD+' products",
    riskCautions: "Quality varies; IV reactions possible; discuss with clinician",
    bestFor: "General physiology / research interest",
    keyEffects: "Coenzyme involved in redox/mitochondrial function",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Longevity",
    categories: ["Longevity"],
  },
  {
    name: "MOTS-c (research)",
    primaryPurpose: "Metabolic / Longevity",
    whatItDoes: "Mitochondrial-derived peptide involved in metabolic signaling",
    commonUses: "Research",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved; unknown risks",
    bestFor: "Cardiometabolic risk reduction (weight, glucose, BP)",
    keyEffects: "Mitochondrial-derived peptide involved in metabolic signaling",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "Limited direct cardiovascular evidence.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Metabolic/Weight",
    categories: ["Longevity"],
  },
  {
    name: "Humanin (research)",
    primaryPurpose: "Mitochondrial / Neuroprotection",
    whatItDoes: "Mitochondrial-derived peptide with cytoprotective signaling (experimental)",
    commonUses: "Research",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved",
    bestFor: "Focus/anxiety/neuro support (often research/region-specific)",
    keyEffects: "Mitochondrial-derived peptide with cytoprotective signaling (experimental)",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Longevity",
    categories: ["Longevity"],
  },
  {
    name: "GHK-Cu (Copper peptide)",
    primaryPurpose: "Skin / Hair",
    whatItDoes: "Signals collagen remodeling and wound repair",
    commonUses: "Topical skincare; hair support products",
    dosageRange: "Topical concentrations vary by product",
    riskCautions: "Skin irritation possible; avoid unverified injectables",
    bestFor: "Tissue repair / skin & hair support",
    keyEffects: "Signals the GH axis; can affect body composition, fluid retention, and glucose",
    evidenceLevel: "Mixed/unclear regulatory status",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Skin irritation possible; avoid unverified injectables",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "Can raise glucose; monitor if on diabetes meds; fluid retention may affect BP/CHF; avoid with active malignancy (per clinical guidance).",
    goalCategory: "GH Axis",
    categories: ["Healing/Recovery", "Longevity", "Skin/Hair"],
  },
  {
    name: "Matrixyl (Palmitoyl pentapeptide)",
    primaryPurpose: "Cosmetic",
    whatItDoes: "Peptide used in cosmetics to support collagen appearance",
    commonUses: "Anti-aging skincare",
    dosageRange: "Topical product-dependent",
    riskCautions: "Irritation/allergy possible",
    bestFor: "Tissue repair / skin & hair support",
    keyEffects: "Supports skin repair/collagen signaling (usually topical products)",
    evidenceLevel: "Mixed/unclear regulatory status",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Irritation/allergy possible",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Skin/Hair",
    categories: ["Skin/Hair"],
  },
  {
    name: "Argireline (Acetyl hexapeptide-8)",
    primaryPurpose: "Cosmetic",
    whatItDoes: "Cosmetic peptide aimed at reducing expression lines",
    commonUses: "Anti-wrinkle skincare",
    dosageRange: "Topical product-dependent",
    riskCautions: "Irritation possible",
    bestFor: "Tissue repair / skin & hair support",
    keyEffects: "Cosmetic peptide aimed at reducing expression lines",
    evidenceLevel: "Mixed/unclear regulatory status",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Irritation possible",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Skin/Hair",
    categories: ["Skin/Hair"],
  },
  {
    name: "Bremelanotide (Vyleesi; PT-141 analog)",
    primaryPurpose: "Sexual health",
    whatItDoes: "Melanocortin receptor agonist; indicated for premenopausal HSDD",
    commonUses: "HSDD (premenopausal women)",
    dosageRange: "1.75 mg SC as needed ≥45 min before; max 1 dose/24h; max 8 doses/month",
    riskCautions: "Can raise BP, nausea/flushing; not for performance enhancement; avoid in uncontrolled HTN/CVD",
    bestFor: "Sexual function / reproductive axis",
    keyEffects: "Melanocortin receptor agonist; indicated for premenopausal HSDD",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "Can raise BP, nausea/flushing; not for performance enhancement; avoid in uncontrolled HTN/CVD",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "Can raise BP/HR; avoid with uncontrolled HTN/CVD; caution with antihypertensives; nausea common.",
    goalCategory: "Sexual Health",
    categories: ["Sexual Health"],
  },
  {
    name: "Kisspeptin (research/clinical research)",
    primaryPurpose: "Reproductive axis",
    whatItDoes: "Stimulates GnRH → LH/FSH release",
    commonUses: "Research: fertility/endocrine testing",
    dosageRange: "N/A (protocol-specific)",
    riskCautions: "Not routine; endocrine effects; clinician supervision",
    bestFor: "Sexual function / reproductive axis",
    keyEffects: "Stimulates GnRH → LH/FSH release",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Sexual Health",
    categories: ["Sexual Health"],
  },
  {
    name: "Oxytocin",
    primaryPurpose: "Neuroendocrine",
    whatItDoes: "Bonding/social neuropeptide; uterotonic in obstetrics",
    commonUses: "Labor/postpartum hemorrhage (medical); research for social effects",
    dosageRange: "Indication-specific dosing (obstetrics)",
    riskCautions: "Serious obstetric risks if misused; do not self-administer",
    bestFor: "Focus/anxiety/neuro support (often research/region-specific)",
    keyEffects: "Bonding/social neuropeptide; uterotonic in obstetrics",
    evidenceLevel: "Mixed/unclear regulatory status",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Serious obstetric risks if misused; do not self-administer",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "Obstetric medication—avoid self-use; interactions managed clinically.",
    goalCategory: "Cognition/Mood",
    categories: ["Cognition/Mood", "Sexual Health"],
  },
  {
    name: "hCG (not a peptide; glycoprotein hormone)",
    primaryPurpose: "Reproductive",
    whatItDoes: "LH-like activity; supports gonadal function",
    commonUses: "Fertility; hypogonadism protocols (medical)",
    dosageRange: "Indication-specific dosing",
    riskCautions: "Thromboembolic/ovarian hyperstimulation risks; prescription required",
    bestFor: "Sexual function / reproductive axis",
    keyEffects: "LH-like activity; supports gonadal function",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Longevity",
    categories: [],
  },
  {
    name: "ANP (Atrial natriuretic peptide)",
    primaryPurpose: "Cardiovascular",
    whatItDoes: "Regulates natriuresis/vasodilation (endogenous)",
    commonUses: "Physiology; research",
    dosageRange: "N/A",
    riskCautions: "Not a self-treatment; significant BP effects",
    bestFor: "Cardiovascular / vascular effects (often hospital/physiology)",
    keyEffects: "Widens blood vessels; can lower blood pressure",
    evidenceLevel: "Physiology/diagnostic target (not a therapy)",
    bottomLine: "Important in biology/diagnostics, not a self-treatment.",
    avoidIf: "Not a medication; do not self-treat with it.",
    cvRating: 2,
    cvNotes: "Key cardiovascular physiology/diagnostic relevance; not used as a self-therapy.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Cardio/Vascular",
    categories: ["Cardio/Vascular"],
  },
  {
    name: "BNP (B-type natriuretic peptide)",
    primaryPurpose: "Cardiovascular",
    whatItDoes: "Marker and mediator in heart failure physiology",
    commonUses: "Diagnostics; physiology",
    dosageRange: "N/A",
    riskCautions: "Not a self-treatment",
    bestFor: "Cardiovascular / vascular effects (often hospital/physiology)",
    keyEffects: "Marker and mediator in heart failure physiology",
    evidenceLevel: "Physiology/diagnostic target (not a therapy)",
    bottomLine: "Important in biology/diagnostics, not a self-treatment.",
    avoidIf: "Not a medication; do not self-treat with it.",
    cvRating: 2,
    cvNotes: "Key cardiovascular physiology/diagnostic relevance; not used as a self-therapy.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Cardio/Vascular",
    categories: ["Cardio/Vascular"],
  },
  {
    name: "Apelin (research)",
    primaryPurpose: "Cardiovascular / Metabolic",
    whatItDoes: "Peptide ligand involved in vascular tone and cardiac function",
    commonUses: "Research",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved",
    bestFor: "Cardiometabolic risk reduction (weight, glucose, BP)",
    keyEffects: "Peptide ligand involved in vascular tone and cardiac function",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 2,
    cvNotes: "Promising mechanisms for cardiac/vascular function, but mainly research-stage.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Metabolic/Weight",
    categories: ["Cardio/Vascular"],
  },
  {
    name: "Adrenomedullin (research)",
    primaryPurpose: "Vascular",
    whatItDoes: "Vasodilatory peptide hormone",
    commonUses: "Research",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved; hypotension risk",
    bestFor: "Cardiovascular / vascular effects (often hospital/physiology)",
    keyEffects: "Vasodilatory peptide hormone",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 2,
    cvNotes: "Promising mechanisms for cardiac/vascular function, but mainly research-stage.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Cardio/Vascular",
    categories: ["Cardio/Vascular"],
  },
  {
    name: "GLP-2 analog (Teduglutide)",
    primaryPurpose: "GI / Short bowel syndrome",
    whatItDoes: "GLP-2 analog increases intestinal absorption and mucosal growth",
    commonUses: "Short bowel syndrome (FDA-approved)",
    dosageRange: "Product-specific dosing (PI)",
    riskCautions: "Risk of GI obstruction, biliary/pancreatic issues; clinician-only",
    bestFor: "General physiology / research interest",
    keyEffects: "GLP-2 analog increases intestinal absorption and mucosal growth",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "Risk of GI obstruction, biliary/pancreatic issues; clinician-only",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "GI/Bone/Other",
    categories: ["GI/Bone/Other"],
  },
  {
    name: "Desmopressin (DDAVP)",
    primaryPurpose: "Endocrine / Hemostasis",
    whatItDoes: "Vasopressin analog; reduces urine output; increases vWF release",
    commonUses: "Central diabetes insipidus; nocturnal enuresis; certain bleeding disorders",
    dosageRange: "Indication-specific dosing",
    riskCautions: "Hyponatremia/seizure risk; requires monitoring",
    bestFor: "Hormone axis support (medical oversight)",
    keyEffects: "Vasopressin analog; reduces urine output; increases vWF release",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "Hyponatremia/seizure risk; requires monitoring",
    cvRating: 1,
    cvNotes: "Limited direct cardiovascular evidence.",
    drugInteractions: "Hyponatremia risk—caution with SSRIs/SNRIs, diuretics; fluid restriction and sodium monitoring.",
    goalCategory: "Metabolic/Weight",
    categories: ["GI/Bone/Other"],
  },
  {
    name: "Calcitonin",
    primaryPurpose: "Bone / Calcium",
    whatItDoes: "Lowers serum calcium; affects bone turnover",
    commonUses: "Hypercalcemia; osteoporosis (limited use)",
    dosageRange: "Product-specific dosing",
    riskCautions: "Cancer risk warning for some uses; nasal irritation",
    bestFor: "Bone strength (fracture risk reduction)",
    keyEffects: "Lowers serum calcium; affects bone turnover",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "Cancer risk warning for some uses; nasal irritation",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "Generally low interaction burden; monitor calcium; follow product guidance.",
    goalCategory: "GI/Bone/Other",
    categories: ["GI/Bone/Other"],
  },
  {
    name: "Teriparatide (Forteo)",
    primaryPurpose: "Bone",
    whatItDoes: "PTH(1-34) analog: stimulates bone formation",
    commonUses: "Severe osteoporosis at high fracture risk",
    dosageRange: "20 mcg SC once daily",
    riskCautions: "Hypercalcemia; orthostatic hypotension; osteosarcoma warning in animals; duration limits per guidelines",
    bestFor: "Bone strength (fracture risk reduction)",
    keyEffects: "PTH(1-34) analog: stimulates bone formation",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "Hypercalcemia; orthostatic hypotension; osteosarcoma warning in animals; duration limits per guidelines",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "Monitor calcium/vitamin D; caution with digoxin (hypercalcemia can increase toxicity risk).",
    goalCategory: "GH Axis",
    categories: ["GI/Bone/Other"],
  },
  {
    name: "Abaloparatide (Tymlos)",
    primaryPurpose: "Bone",
    whatItDoes: "PTHrP analog: anabolic bone agent",
    commonUses: "Osteoporosis in postmenopausal women at high risk",
    dosageRange: "Product-specific dosing (PI)",
    riskCautions: "Hypercalcemia; osteosarcoma warning in animals",
    bestFor: "Bone strength (fracture risk reduction)",
    keyEffects: "PTHrP analog: anabolic bone agent",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "Hypercalcemia; osteosarcoma warning in animals",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "Monitor calcium/vitamin D; caution with digoxin (hypercalcemia can increase toxicity risk).",
    goalCategory: "GH Axis",
    categories: ["GI/Bone/Other"],
  },
  {
    name: "Vasopressin",
    primaryPurpose: "Critical care",
    whatItDoes: "V1/V2 agonist; vasoconstriction and water retention",
    commonUses: "Shock, variceal bleeding (hospital)",
    dosageRange: "Hospital protocols only",
    riskCautions: "Severe ischemic risks; ICU-only",
    bestFor: "General physiology / research interest",
    keyEffects: "V1/V2 agonist; vasoconstriction and water retention",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "Severe ischemic risks; ICU-only",
    cvRating: 3,
    cvNotes: "Clinically important in acute care settings; not a chronic 'heart health' therapy.",
    drugInteractions: "ICU-only; vasoconstriction—drug interactions managed in hospital protocols.",
    goalCategory: "Cardio/Vascular",
    categories: ["Cardio/Vascular"],
  },
  {
    name: "CGRP (Calcitonin gene-related peptide)",
    primaryPurpose: "Neurovascular",
    whatItDoes: "Pain/vasodilation mediator; target in migraine therapy",
    commonUses: "Migraine biology; targeted by monoclonal antibodies/small molecules",
    dosageRange: "N/A (endogenous target)",
    riskCautions: "Not a self-treatment",
    bestFor: "Cardiovascular / vascular effects (often hospital/physiology)",
    keyEffects: "Widens blood vessels; can lower blood pressure",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "Not a self-treatment",
    cvRating: 1,
    cvNotes: "Limited direct cardiovascular evidence.",
    drugInteractions: "Generally low interaction burden; monitor calcium; follow product guidance.",
    goalCategory: "Cardio/Vascular",
    categories: ["GI/Bone/Other"],
  },
  {
    name: "Substance P",
    primaryPurpose: "Pain signaling",
    whatItDoes: "Neuropeptide involved in pain and inflammation",
    commonUses: "Research/physiology",
    dosageRange: "N/A",
    riskCautions: "Not a self-treatment",
    bestFor: "General physiology / research interest",
    keyEffects: "Neuropeptide involved in pain and inflammation",
    evidenceLevel: "Physiology/diagnostic target (not a therapy)",
    bottomLine: "Important in biology/diagnostics, not a self-treatment.",
    avoidIf: "Not a medication; do not self-treat with it.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "GI/Bone/Other",
    categories: ["GI/Bone/Other"],
  },
  {
    name: "Bivalirudin",
    primaryPurpose: "Anticoagulation",
    whatItDoes: "Direct thrombin inhibitor (peptide)",
    commonUses: "PCI anticoagulation (hospital)",
    dosageRange: "Hospital protocols only",
    riskCautions: "Bleeding risk; medical supervision",
    bestFor: "General physiology / research interest",
    keyEffects: "Direct thrombin inhibitor (peptide)",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "Bleeding risk; medical supervision",
    cvRating: 4,
    cvNotes: "Hospital cardiovascular use with strong clinical evidence for specific acute indications (not wellness).",
    drugInteractions: "High bleeding risk with anticoagulants/antiplatelets/NSAIDs; hospital-only protocols.",
    goalCategory: "Cardio/Vascular",
    categories: ["Cardio/Vascular"],
  },
  {
    name: "Eptifibatide",
    primaryPurpose: "Antiplatelet",
    whatItDoes: "GPIIb/IIIa inhibitor (peptide)",
    commonUses: "ACS/PCI (hospital)",
    dosageRange: "Hospital protocols only",
    riskCautions: "Bleeding/thrombocytopenia risk",
    bestFor: "General physiology / research interest",
    keyEffects: "GPIIb/IIIa inhibitor (peptide)",
    evidenceLevel: "FDA-approved Rx (labeled use)",
    bottomLine: "Strongest data when used for its labeled indication under clinician guidance.",
    avoidIf: "Bleeding/thrombocytopenia risk",
    cvRating: 4,
    cvNotes: "Hospital cardiovascular use with strong clinical evidence for specific acute indications (not wellness).",
    drugInteractions: "High bleeding risk with anticoagulants/antiplatelets/NSAIDs; hospital-only protocols.",
    goalCategory: "Cardio/Vascular",
    categories: ["Cardio/Vascular"],
  },
  {
    name: "Melanotan II (research)",
    primaryPurpose: "Pigmentation / Sexual",
    whatItDoes: "Melanocortin agonist (experimental)",
    commonUses: "Tanning and libido discussions",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved; nausea, BP effects, hyperpigmentation; melanoma concern; avoid",
    bestFor: "Sexual function / reproductive axis",
    keyEffects: "Melanocortin agonist (experimental)",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "BP effects possible; avoid with uncontrolled HTN; avoid if melanoma/skin cancer risk.",
    goalCategory: "Skin/Hair",
    categories: ["Skin/Hair", "Sexual Health"],
  },
  {
    name: "α-MSH analogs (research)",
    primaryPurpose: "Inflammation / Pigmentation",
    whatItDoes: "Melanocortin pathway signaling",
    commonUses: "Research",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved",
    bestFor: "General physiology / research interest",
    keyEffects: "Melanocortin pathway signaling",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "GI/Bone/Other",
    categories: [],
  },
  {
    name: "Defensins (research)",
    primaryPurpose: "Antimicrobial",
    whatItDoes: "Innate immune antimicrobial peptides",
    commonUses: "Research",
    dosageRange: "N/A",
    riskCautions: "Not FDA-approved",
    bestFor: "Immune modulation / antimicrobial research",
    keyEffects: "Innate immune antimicrobial signaling (experimental)",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Immune/Anti-inf",
    categories: ["Immune/Anti-inf"],
  },
  {
    name: "Thymopentin (research/region-specific)",
    primaryPurpose: "Immune",
    whatItDoes: "Thymic peptide fragment studied for immune modulation",
    commonUses: "Research",
    dosageRange: "N/A",
    riskCautions: "Regulatory status varies",
    bestFor: "Immune modulation / antimicrobial research",
    keyEffects: "Thymic peptide fragment studied for immune modulation",
    evidenceLevel: "Research/compounded/adjunct (no established FDA indication)",
    bottomLine: "Popular in research/compounding; human safety/benefit not well-established.",
    avoidIf: "Avoid self-injection and unverified sources; discuss with a clinician.",
    cvRating: 1,
    cvNotes: "No solid direct cardiovascular outcomes evidence; any benefit is indirect or unproven.",
    drugInteractions: "No well-established interaction profile for non-approved peptides; avoid combining multiple research compounds; discuss meds with clinician.",
    goalCategory: "Immune/Anti-inf",
    categories: ["Immune/Anti-inf"],
  },
]

export function findPeptide(name: string): PeptideKnowledge | undefined {
  const lower = name.toLowerCase()
  return PEPTIDE_KNOWLEDGE.find(p => p.name.toLowerCase().includes(lower))
}

export function searchPeptides(query: string): PeptideKnowledge[] {
  if (!query.trim()) return PEPTIDE_KNOWLEDGE
  const lower = query.toLowerCase()
  return PEPTIDE_KNOWLEDGE.filter(p =>
    p.name.toLowerCase().includes(lower) ||
    p.primaryPurpose.toLowerCase().includes(lower) ||
    p.keyEffects.toLowerCase().includes(lower) ||
    p.whatItDoes.toLowerCase().includes(lower) ||
    p.goalCategory.toLowerCase().includes(lower) ||
    p.bestFor.toLowerCase().includes(lower)
  )
}

export function getPeptidesByCategory(category: string): PeptideKnowledge[] {
  return PEPTIDE_KNOWLEDGE.filter(p => p.goalCategory === category || p.categories.includes(category))
}

export const GOAL_CATEGORIES = [
  "Metabolic/Weight",
  "Healing/Recovery",
  "GH Axis",
  "Muscle/Performance",
  "Longevity",
  "Cognition/Mood",
  "Sleep",
  "Immune/Anti-inf",
  "Skin/Hair",
  "Sexual Health",
  "Cardio/Vascular",
  "GI/Bone/Other",
] as const

export type GoalCategory = typeof GOAL_CATEGORIES[number]