// Full peptide master list from Peptides_Master_List_FULL_Explainers_CV_Interactions_Dropdowns.xlsx
export const ALL_PEPTIDES = [
  'Semaglutide (Ozempic/Wegovy)',
  'Tirzepatide (Mounjaro/Zepbound)',
  'Liraglutide (Saxenda/Victoza)',
  'Exenatide (Byetta/Bydureon)',
  'Dulaglutide (Trulicity)',
  'Pramlintide (Symlin)',
  'Cagrilintide',
  'Retatrutide',
  'Leptin / Metreleptin',
  'Glucagon',
  'Tesamorelin',
  'Somatropin (HGH)',
  'Sermorelin',
  'CJC-1295',
  'Ipamorelin',
  'GHRP-2',
  'GHRP-6',
  'BPC-157',
  'TB-500 (Thymosin Beta-4 Fragment)',
  'Thymosin Beta-4',
  'Thymosin Alpha-1',
  'LL-37',
  'VIP (Vasoactive Intestinal Peptide)',
  'KPV',
  'Semax',
  'Selank',
  'Cerebrolysin',
  'Dihexa',
  'DSIP (Delta Sleep-Inducing Peptide)',
  'Epitalon / Epithalon',
  'NAD+',
  'MOTS-c',
  'Humanin',
  'GHK-Cu (Copper Peptide)',
  'Matrixyl (Palmitoyl Pentapeptide)',
  'Argireline (Acetyl Hexapeptide-8)',
  'Bremelanotide (PT-141)',
  'Melanotan II',
  'Kisspeptin',
  'Oxytocin',
  'hCG',
  'ANP (Atrial Natriuretic Peptide)',
  'BNP (B-type Natriuretic Peptide)',
  'Apelin',
  'Adrenomedullin',
  'Teduglutide (GLP-2 Analog)',
  'Desmopressin (DDAVP)',
  'Calcitonin',
  'Teriparatide (Forteo)',
  'Abaloparatide (Tymlos)',
  'Vasopressin',
  'CGRP (Calcitonin Gene-Related Peptide)',
  'Substance P',
  'Bivalirudin',
  'Eptifibatide',
  'Alpha-MSH Analogs',
  'Defensins',
  'Thymopentin',
  // Additional commonly tracked
  'IGF-1 LR3',
  'AOD-9604',
  'Hexarelin',
  'CJC-1295 (no DAC)',
  'Follistatin 344',
  'ACE-031',
  'GHK',
  'PT-141',
]
