-- GENERATED by scripts/generate-shop-seed.mjs — do not edit by hand.
-- Source of truth: src/lib/shop/catalogue.ts
--
-- Idempotent: products upsert on slug, lots insert only when absent. Safe to
-- re-run after a price change. Apply shop_schema.sql first.

insert into public.shop_products
  (slug, name, compound_id, size_value, size_unit, price_cents, blend_of, active, sort_order)
values ('glp-3-30mg', 'GLP-3 (Retatrutide)', 'retatrutide', 30, 'mg', 12500, null, true, 1)
on conflict (slug) do update set
  name = excluded.name, price_cents = excluded.price_cents,
  active = excluded.active, sort_order = excluded.sort_order;

insert into public.shop_products
  (slug, name, compound_id, size_value, size_unit, price_cents, blend_of, active, sort_order)
values ('vip-5mg', 'VIP', 'vip-vip', 5, 'mg', 3000, null, true, 2)
on conflict (slug) do update set
  name = excluded.name, price_cents = excluded.price_cents,
  active = excluded.active, sort_order = excluded.sort_order;

insert into public.shop_products
  (slug, name, compound_id, size_value, size_unit, price_cents, blend_of, active, sort_order)
values ('mots-c-10mg', 'MOTS-c', 'mots-c', 10, 'mg', 3000, null, true, 3)
on conflict (slug) do update set
  name = excluded.name, price_cents = excluded.price_cents,
  active = excluded.active, sort_order = excluded.sort_order;

insert into public.shop_products
  (slug, name, compound_id, size_value, size_unit, price_cents, blend_of, active, sort_order)
values ('selank-5mg', 'Selank', 'selank', 5, 'mg', 3000, null, true, 4)
on conflict (slug) do update set
  name = excluded.name, price_cents = excluded.price_cents,
  active = excluded.active, sort_order = excluded.sort_order;

insert into public.shop_products
  (slug, name, compound_id, size_value, size_unit, price_cents, blend_of, active, sort_order)
values ('semax-5mg', 'Semax', 'semax', 5, 'mg', 3000, null, true, 5)
on conflict (slug) do update set
  name = excluded.name, price_cents = excluded.price_cents,
  active = excluded.active, sort_order = excluded.sort_order;

insert into public.shop_products
  (slug, name, compound_id, size_value, size_unit, price_cents, blend_of, active, sort_order)
values ('klow-80mg', 'KLOW', null, 80, 'mg', 10000, array['ghk-cu-copper-peptide', 'bpc-157', 'tb-500', 'kpv'], true, 6)
on conflict (slug) do update set
  name = excluded.name, price_cents = excluded.price_cents,
  active = excluded.active, sort_order = excluded.sort_order;

insert into public.shop_products
  (slug, name, compound_id, size_value, size_unit, price_cents, blend_of, active, sort_order)
values ('nad-1000mg', 'NAD+', 'nad', 1000, 'mg', 7500, null, true, 7)
on conflict (slug) do update set
  name = excluded.name, price_cents = excluded.price_cents,
  active = excluded.active, sort_order = excluded.sort_order;

insert into public.shop_lots
  (product_id, lot_code, assay_state, assay_type, purity_pct, components,
   label_mg, measured_total_mg, assay_expected_at, mfg, exp, shelf_life, is_current)
select p.id, 'JA-102107', 'assayed', 'purity', 99.62, null,
       30, null, null, '2026-01', '2028-01', 'USE WITHIN 28 DAYS · 2–8 °C', true
from public.shop_products p where p.slug = 'glp-3-30mg'
and not exists (select 1 from public.shop_lots l where l.product_id = p.id
  and coalesce(l.lot_code, '') = coalesce('JA-102107', ''));

insert into public.shop_lots
  (product_id, lot_code, assay_state, assay_type, purity_pct, components,
   label_mg, measured_total_mg, assay_expected_at, mfg, exp, shelf_life, is_current)
select p.id, 'JA-68243', 'assayed', 'purity', 99.73, null,
       30, null, null, null, null, 'USE WITHIN 28 DAYS · 2–8 °C', false
from public.shop_products p where p.slug = 'glp-3-30mg'
and not exists (select 1 from public.shop_lots l where l.product_id = p.id
  and coalesce(l.lot_code, '') = coalesce('JA-68243', ''));

insert into public.shop_lots
  (product_id, lot_code, assay_state, assay_type, purity_pct, components,
   label_mg, measured_total_mg, assay_expected_at, mfg, exp, shelf_life, is_current)
select p.id, 'JA-63071', 'assayed', 'purity', 99.46, null,
       30, null, null, null, null, 'USE WITHIN 28 DAYS · 2–8 °C', false
from public.shop_products p where p.slug = 'glp-3-30mg'
and not exists (select 1 from public.shop_lots l where l.product_id = p.id
  and coalesce(l.lot_code, '') = coalesce('JA-63071', ''));

insert into public.shop_lots
  (product_id, lot_code, assay_state, assay_type, purity_pct, components,
   label_mg, measured_total_mg, assay_expected_at, mfg, exp, shelf_life, is_current)
select p.id, 'JA-102111', 'assayed', 'purity', 99.114, null,
       10, 12.33, null, '2026-01', '2028-01', 'USE WITHIN 28 DAYS · 2–8 °C', true
from public.shop_products p where p.slug = 'mots-c-10mg'
and not exists (select 1 from public.shop_lots l where l.product_id = p.id
  and coalesce(l.lot_code, '') = coalesce('JA-102111', ''));

insert into public.shop_lots
  (product_id, lot_code, assay_state, assay_type, purity_pct, components,
   label_mg, measured_total_mg, assay_expected_at, mfg, exp, shelf_life, is_current)
select p.id, 'JA-102113', 'assayed', 'composition', null, '[{"name":"GHK-Cu","mg":57.45},{"name":"BPC-157","mg":11.12},{"name":"TB-500 (TB4)","mg":10.88},{"name":"KPV","mg":11.2}]'::jsonb,
       80, 90.65, null, '2026-01', '2028-01', 'USE WITHIN 28 DAYS · 2–8 °C', true
from public.shop_products p where p.slug = 'klow-80mg'
and not exists (select 1 from public.shop_lots l where l.product_id = p.id
  and coalesce(l.lot_code, '') = coalesce('JA-102113', ''));

insert into public.shop_lots
  (product_id, lot_code, assay_state, assay_type, purity_pct, components,
   label_mg, measured_total_mg, assay_expected_at, mfg, exp, shelf_life, is_current)
select p.id, null, 'pending', 'purity', null, null,
       5, null, '2026-10', null, null, 'USE WITHIN 28 DAYS · 2–8 °C', true
from public.shop_products p where p.slug = 'vip-5mg'
and not exists (select 1 from public.shop_lots l where l.product_id = p.id
  and coalesce(l.lot_code, '') = coalesce(null, ''));

insert into public.shop_lots
  (product_id, lot_code, assay_state, assay_type, purity_pct, components,
   label_mg, measured_total_mg, assay_expected_at, mfg, exp, shelf_life, is_current)
select p.id, null, 'pending', 'purity', null, null,
       5, null, '2026-10', null, null, 'USE WITHIN 28 DAYS · 2–8 °C', true
from public.shop_products p where p.slug = 'selank-5mg'
and not exists (select 1 from public.shop_lots l where l.product_id = p.id
  and coalesce(l.lot_code, '') = coalesce(null, ''));

insert into public.shop_lots
  (product_id, lot_code, assay_state, assay_type, purity_pct, components,
   label_mg, measured_total_mg, assay_expected_at, mfg, exp, shelf_life, is_current)
select p.id, null, 'pending', 'purity', null, null,
       5, null, '2026-10', null, null, 'USE WITHIN 28 DAYS · 2–8 °C', true
from public.shop_products p where p.slug = 'semax-5mg'
and not exists (select 1 from public.shop_lots l where l.product_id = p.id
  and coalesce(l.lot_code, '') = coalesce(null, ''));

insert into public.shop_lots
  (product_id, lot_code, assay_state, assay_type, purity_pct, components,
   label_mg, measured_total_mg, assay_expected_at, mfg, exp, shelf_life, is_current)
select p.id, null, 'pending', 'purity', null, null,
       1000, null, '2026-10', null, null, 'USE WITHIN 28 DAYS · 2–8 °C', true
from public.shop_products p where p.slug = 'nad-1000mg'
and not exists (select 1 from public.shop_lots l where l.product_id = p.id
  and coalesce(l.lot_code, '') = coalesce(null, ''));
